### ISSUE TITLE
Deliver the container to the github container registry

### ISSUE THREAD

**Issue by brucellino** [mmul-it/kpa#10]
I would like to propose that the `kpa` container be built during the github actions workflow. Using the token issued to the github action pipeline, we can build and push the container directly to github packages.

**Comment by rascasoft** [comment]
At the moment a container is produced in quay (https://quay.io/repository/mmul/kpa) for every push inside the repo.
Releases are produced arbitrarily, depending on the overall status and on feature integrations, and in any case they corresponds to the container's release.
At the moment we have one release 1.0.0 (`docker pull quay.io/mmul/kpa:v1.0.0`) and the latest/main one (`docker pull quay.io/mmul/kpa:latest`).

How much effort is requested to bring the produced release inside GitHub considering the fact that we have already a GitHub Actions workflow in place? Would you mind to propose a pull request for it?

**Comment by brucellino** [comment]
Happy to send a PR for it. It'll involve a subsequent stage to invoke a Docker build ; Docker push.
Ideally, I'd propose a Packer template with tagging and pushing post-processor. We can discuss in the PR when it comes. Thanks!

**Comment by rascasoft** [comment]
One thing to consider on using the GitHub registry is that maybe this can also fix https://github.com/mmul-it/kpa/issues/8 a problem that is affecting kpa since almost the beginning.

**Comment by rascasoft** [comment]
@brucellino any news on the PR?

**Comment by rascasoft** [comment]
@brucellino I've changed the workflow for producing new images, and now we have this https://github.com/mmul-it/kpa/actions/runs/5740805583 that is meant to build directly from GitHub and then push to Quay.
I'm closing this issue because at the moment we don't need to rely on GitHub registry, since we can keep using Quay, but in the future it will be a matter of a small change in the Actions workflow, so we're all good here.

**Comment by rascasoft** [comment]
@brucellino actually seeing the way quay.io treats the pushed images (it doesn't give the status since the build was not made there), it might still be a better option to push in GitHub registry, so I'm reopening this and start the work to move everything under GitHub.
