### ISSUE TITLE
Can we remove chrome?

### ISSUE THREAD

**Issue by brucellino** [mmul-it/kpa#12]
Google chrome is installed in the build container - I'd like to understand where this requirement comes from. Naively it seems like overkill to include a browser in the container, perhaps it's required for pandoc?

**Comment by rascasoft** [comment]
Chrome is a Marp dependency (https://github.com/marp-team/marp-cli/blob/main/README.md#try-it-now) and so it would be impossible to remove it and still have marp-cli working.
Chromium and Edge are the other alternatives, that is why I chose the less impacting.

**Comment by brucellino** [comment]
ok, makes sense. thanks!
